MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.fpn_ResNet50_conv5_body
  FASTER_RCNN: True
  VCOCO_ON: True # BBOX_REG_WEIGHTS: (2., 2., 1., 1.)
RESNETS:
  IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/resnet50_caffe.pth'
NUM_GPUS: 1
SOLVER:
  WARM_UP_ITERS: 0
  FASTER_RCNN_WEIGHT: 1.0
  TYPE: SGD
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.001  # different lr and steps
  GAMMA: 0.1
  MAX_ITER: 200000
  STEPS: [0, 100000]
  VAL_ITER: 1000
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: False
  MULTILEVEL_RPN: True
FAST_RCNN:
#  CONV_HEAD_DIM: 256
  ROI_BOX_HEAD: fast_rcnn_heads.roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
HICO:
  USE_PRECOMP_BOX: False
  USE_SPATIAL: False
  KEYPOINTS_ON: False
  USE_UNION_FEAT: False
  TRAIN_BATCH_SIZE_PER_IM: 512
  KP_HUMAN_NUM_PER_IM: 16
  USE_ORIGIN: False
  LATE_FUƒSION: False
  TRIPLETS_NUM_PER_IM: 16
  MLP_HEAD_DIM: 256
  HEATMAP_KERNEL_SIZE: 7
  PART_CROP_SIZE: 7
  AFFINITY_WEIGHT: 0.1
#  TEST_HUMAN_SCORE_THRESH: 0.
#  TEST_TARGET_OBJECT_SCORE_THRESH: 0.
KRCNN:
  LOSS_WEIGHT: 0.1
#  ROI_KEYPOINTS_HEAD: hoi_keypoint_rcnn_heads.roi_pose_head_v1convX
  NUM_STACKED_CONVS: 8
  NUM_KEYPOINTS: 17
  USE_DECONV_OUTPUT: True
  CONV_INIT: MSRAFill
  CONV_HEAD_DIM: 512
  UP_SCALE: 2
  HEATMAP_SIZE: 64  # ROI_XFORM_RESOLUTION (14) * UP_SCALE (2) * USE_DECONV_OUTPUT (2)
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14
  ROI_XFORM_SAMPLING_RATIO: 2
  KEYPOINT_CONFIDENCE: bbox
  NMS_OKS: False
#  HUMAN_BRANCH_WEIGHTS: 1.0
TRAIN:
  SCALES: (800,)
  MAX_SIZE: 1333
  BATCH_SIZE_PER_IM: 2048  # keep as many as possible rois for re-sample in next stage
  FG_FRACTION: 1.  # same reason as batch_size, ToDo
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  FREEZE_CONV_BODY: False
  FREEZE_RPN_BODY: False
  FREEZE_FASTER_RCNN: False
  SNAPSHOT_ITERS: 1000
  FG_THRESH: 0.5
  USE_GT: False
TEST:
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.3 #
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
  DETECTIONS_PER_IM: 0  # The paper doesn't state how many detections to keep
